### ISSUE TITLE
I don't get this. How do i do this

### ISSUE THREAD

**Issue by tjw0lf** [erikdubois/Sardi#1]
if i want it all one color i do not get what this means to do. Doesn't explain a lot
 find -name "*.svg" -exec sed -i 's/6997c7/d44d3b/g' {}  \;

**Comment by erikdubois** [comment]
it looks for svg files (in essence just text file) and replaces the first colour with the second and keeps on doing that till the last svg
color one : 6997c7
color two : d44d3b

try gpick or gcolor2 to find out the hexadecimal code or paste in in google that will work too

you run this in a terminal in the folder you would like to change
