### ISSUE TITLE
some kde (app) icons missing

### ISSUE THREAD

**Issue by ahjolinna** [erikdubois/Sardi#11]
I know that u really dont care about KDE, but still:

ktorrent:
![image](https://cloud.githubusercontent.com/assets/6993072/21964997/09de05d6-db5f-11e6-9072-64609373502c.png)
![image](https://cloud.githubusercontent.com/assets/6993072/21964989/cde155ba-db5e-11e6-8502-e49893cc85cf.png)
konversation:
![image](https://cloud.githubusercontent.com/assets/6993072/21965001/3b679a54-db5f-11e6-8bdd-bfc167c62db1.png)
![image](https://cloud.githubusercontent.com/assets/6993072/21965006/5c8a0640-db5f-11e6-8d2c-8edf385c508e.png)
system-settings (maybe?):
![image](https://cloud.githubusercontent.com/assets/6993072/21965011/6fe4f696-db5f-11e6-8a8e-8d5d48b88b6a.png)
dolphin(settings): 
![image](https://cloud.githubusercontent.com/assets/6993072/21965016/a87a6176-db5f-11e6-9fac-11b374845fef.png)

I will add more as I notice them

**Comment by erikdubois** [comment]
I have no ambition to solve every issues for every application on KDE. I will keep supporting it on a superficial level though.
