### ISSUE TITLE
Icon Requests

### ISSUE THREAD

**Issue by gitJWR** [erikdubois/Sardi#117]
Bitwarden  https://bitwarden.com/  Icon=bitwarden
Brave  https://brave.com/  Icon=brave
Simplenote  https://simplenote.com/  Icon=simplenote
Workflowy  https://workflowy.com/  Icon=workflowy

(I'm on ArcoLinux 18.9.5)

**Comment by erikdubois** [comment]
bitwarden done

**Comment by erikdubois** [comment]
brave done

**Comment by erikdubois** [comment]
simplenote done

**Comment by erikdubois** [comment]
workflowy separate issue
