### ISSUE TITLE
2 icons missing + 1 update

### ISSUE THREAD

**Issue by ahjolinna** [erikdubois/Sardi#12]
[mpc-qt](https://github.com/cmdrkotori/mpc-qt/), [cpu-x](https://github.com/X0rg/CPU-X).

and now when the [discord linux client finally got a stable version](https://twitter.com/discordapp/status/818978061903241218), it would be nice if you could change the "discord-canary" icon (aka testing version) to yellow/orange (#f7a41a) ...as you can install side by side....the "stable" version should stay the same

update:[ SUSE Advanced X Configuration V3 / SAX3](https://github.com/openSUSE/sax3/tree/master/src/modules.d) has icon missing

------
PS. I have my own personal [MPV-conf-build](https://github.com/ahjolinna/mpv-conf), I was wondering do u any ideas for a icon/logo? (if u don't mind)

**Comment by erikdubois** [comment]
cpu-x done

**Comment by erikdubois** [comment]
mpc-qt done

**Comment by erikdubois** [comment]
make separate issue for discord if still needed
