### ISSUE TITLE
Icon Requests ;)

### ISSUE THREAD

**Issue by ghost** [erikdubois/Sardi#13]
-ePSXe
Name=ePSXe
Icon=/usr/share/pixmaps/epsxe.png
Exec=/usr/bin/epsxe
-Lollypop.
Icon=/usr/share/applications/org.gnome.Lollypop
-Qt Video 4 Linux Utility
Icon=/usr/share/icons/hicolor/[multiple sizes from 16x16 to 64x64]/apps/qv4l2.png
-Xonotic
 Icon=usr/share/icons/hicolor/[multiple sizes from 16x16 to 128x128]/apps/xonotic.png

**Comment by erikdubois** [comment]
lollypop should be fixed

**Comment by erikdubois** [comment]
epsxe fixed

**Comment by erikdubois** [comment]
qv4l2 exists already

**Comment by erikdubois** [comment]
xonotic is done
