### ISSUE TITLE
Icons request 

### ISSUE THREAD

**Issue by EliaHKM** [erikdubois/Sardi#15]
Hi, thank you for your hard working and beautiful icons.
i have some unthemed icons : 
1- epsxe 2- ppsspp 3- qjoypad 4-opendesktop 5-rambox

Thanks in advanced 
peace.

**Comment by erikdubois** [comment]
epsxe done

**Comment by erikdubois** [comment]
ppsspp done

**Comment by erikdubois** [comment]
qjoypad done

**Comment by erikdubois** [comment]
more information required for opendesktop
make separate issue please
check quidelines

**Comment by erikdubois** [comment]
rambox done
