### ISSUE TITLE
few new (and older) KDE apps (+ 2 none)

### ISSUE THREAD

**Issue by ahjolinna** [erikdubois/Sardi#19]
lest start with the newer stuff first:

KDE team is working on two new music apps : [elisa](https://github.com/KDE/elisa) & [babe](https://github.com/KDE/babe)

email client: [kube](https://github.com/KDE/kube)

[koko](https://github.com/KDE/koko) an Image Gallery application 

the older one:

[kup](https://github.com/spersson/Kup/) (backup app)
[
KDE IM Log Viewer](https://github.com/KDE/ktp-text-ui)
Icon=kde-im-log-viewer

[kwave](https://github.com/KDE/kwave), a sound editor for KDE

[qdirstat](https://github.com/shundhammer/qdirstat) disk usage utility (successor to kdirstat)

-----

non-kde 

[fetchpkg](https://github.com/deadhead420/fetchpkg) CLI frontend for pacman / AUR

[vulkanCapsViewer](https://github.com/SaschaWillems/VulkanCapsViewer) -Vulkan Hardware Capability Viewer

------

PS. if you are intrested, I found a python 3 script that changes your wallpaper from wallhaven.cc (works on linux and windows): https://alpha.wallhaven.cc/forums/thread/857

**Comment by ahjolinna** [comment]
(moved comment here)
I thought I forgot something: KDE's new comic book reader [Peruse](https://peruse.kde.org/) : https://github.com/KDE/peruse

has 2 "apps" : [peruse](https://github.com/KDE/peruse/tree/master/src/app/icon) & [peruse-creator](https://github.com/KDE/peruse/tree/master/src/creator/icon) (icon names)

**Comment by erikdubois** [comment]
on the to do list

**Comment by ahjolinna** [comment]
good...oh, and a while ago the popular Qt browser QupZilla has now become part of KDE and got renamed as Falkon : [phoronix news link](https://www.phoronix.com/scan.php?page=news_item&px=QupZilla-Becomes-Falkon)....currently there is no new logo so they still use the [old one ](https://phabricator.kde.org/source/falkon/browse/master/linux/hicolor/256x256/apps/qupzilla.png)

**Comment by erikdubois** [comment]
i will postpone this one till we do ArcoLinuxD-Plasma

**Comment by erikdubois** [comment]
kwave is done

**Comment by erikdubois** [comment]
qdirstat done

**Comment by erikdubois** [comment]
Icon=kde-im-log-viewer was ok

**Comment by erikdubois** [comment]
kup is done

**Comment by erikdubois** [comment]
koko done

**Comment by erikdubois** [comment]
elisa done

**Comment by erikdubois** [comment]
babe done

**Comment by ahjolinna** [comment]
what do you think about the toolbar icons (for example in dolphin) aren't they too light?

**Comment by erikdubois** [comment]
will take a look 
but they are everywhere the same
and some of them are set by the theme - sound icon I think is one
do not know if that is the case in deepin

**Comment by ahjolinna** [comment]
there is [papirus](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme) icon theme, which is mostly focusing on KDE and it has few variation to fit its different kvantum themes they make. You could maybe check how/what they do.

I know that papirus has two version for light and dark themes

**Comment by ahjolinna** [comment]
it seems babe media player is now [vvave](https://github.com/KDE/vvave)

**Comment by erikdubois** [comment]
we need to know the icon name for it then

**Comment by erikdubois** [comment]
elisa improved

**Comment by erikdubois** [comment]
can we close this long list
can not make heads or tails from it
one icon in one issue
