### ISSUE TITLE
some missing icons, mostly KDE stuff

### ISSUE THREAD

**Issue by ahjolinna** [erikdubois/Sardi#2]
I use KDE/chakraOS (plasma5.7 beta), here are some of icons that are missing, more KDE specific:
- KDE-Services, "system-settings->icons->Emoticons", database-chakra(kcm-pacman-repoeditor), "system-settings->(network)Settings->Cookies & Browser Identification, and the system-settings Configure button, system-settings->Search->Plasma Search-> Audio
- some other problems(100% white icon against white breeze theme backround):  system-settings-> Applications and in "Window Managment" there 3 icons: "Window Behavior" "KWin Scripts" and Windows Rules.
- general apps: makemkv, obs, SVPManager, DiscordCanary, vivaldi-stable, teamviewer, franz, YACReaderLibrary & YACReader (same app), t-lasku, donations
-  some renaming/updating.: qmplay2->QMPlay2, cmplayer->bomi (has new logo also now)

I havent checked every version of Sardi, I mostly used the "Flat Majestic" version.

**Comment by erikdubois** [comment]
Not sure if I will ever support KDE - I am not really a fan of the KDE desktop.
I need to protect myself from too much work and restrict it somehow.
For now you can go to /usr/share/applications
open the .desktop files and see what the code is for the icon
icon=nameoficon
and change it manually to change it to an icon that already exists.

example clementine
...
Exec=clementine %U
TryExec=clementine
Icon=clementine
Terminal=false
Categories=AudioVideo;Player;Qt;Audio;
StartupNotify=false

...

also a tip harcodefixer from foggalong changes hardcoded links - this may fix some things as well
good luck

**Comment by ahjolinna** [comment]
I understand not focusing on KDE, but this only needs few fixes...also KDE is almost completely different beast with plasma 5.7 mostly thanks to Qt5.7.... should arrive in few days... I would recommend trying the [kde-neon](http://neon.kde.org/) project, even I was personally surprised how fast and smooth it was.... or [manjaro-kde](http://sourceforge.net/projects/manjarolinux/files/release/16.06.1/kde/manjaro-kde-16.06.1-x86_64.iso), oc [ChakraOS](http://chakraos.org/) and [KaOS](https://kaosx.us/) are also great options

PS. it seems on "gamingonlinux" community KDE is the biggest DE, according to these [statistics](https://www.gamingonlinux.com/users/statistics)..in general its in top 3, depends on distro (where there)...btw. also that ubuntu went with Qt5 with it's Unity, that will make Qt the biggest toolkit.

**Comment by erikdubois** [comment]
never say never

**Comment by erikdubois** [comment]
and there we are. Plasma is supported.
could you download the latest sardi version here  and see what you are missing
https://sourceforge.net/projects/sardi/files/?source=directory

**Comment by ahjolinna** [comment]
well few things, first some apps missing (in ccr):: 
[YACReader](http://www.yacreader.com/), [franz](http://meetfranz.com/), [Vivaldi](https://vivaldi.com/?lang=en), [makemkv](http://www.makemkv.com/), [mkv-extractor-qt5](https://www.linux-apps.com/p/1131021/), [SVP4/SVPManager](https://www.svp-team.com/wiki/Main_Page),  [t-lasku](http://helineva.net/t-lasku/), [KDE-Services](https://www.kde-look.org/content/show.php/KDE-Services?content=147065), [xperia-theme-creator](https://chakralinux.org/ccr/packages.php?ID=7248), [xperia-flashtool](https://chakralinux.org/ccr/packages.php?ID=7286), [Master PDF Editor](https://chakralinux.org/ccr/packages.php?ID=6747)

I maintain most of those ccr pkgs, so if u have problems tell me...I have like [116 ccr pkgs](https://chakralinux.org/ccr/packages.php?K=ahjolinna&SeB=m) :D 

repo apps;
calligragemini, [obs](https://obsproject.com/)

few icon problems with breeze(light)
on dolphin :
![spectacle f19259](https://cloud.githubusercontent.com/assets/6993072/17524448/548e3350-5e67-11e6-8017-985da263101e.png)
system-settings: ![spectacle k21327](https://cloud.githubusercontent.com/assets/6993072/17524536/b5f53e9a-5e67-11e6-922a-99480009df6d.png)

![spectacle j31470](https://cloud.githubusercontent.com/assets/6993072/17525180/4e74dee4-5e6a-11e6-88fb-b22112dac279.png)

thats mostly it

**Comment by erikdubois** [comment]
Have you made a script to install your apps
That would be helpful

Sent from my iPad, embrace the typos and the short answers

**Comment by erikdubois** [comment]
check again with the latest version 7,3,11

i recognize programs I have made icons for

**Comment by erikdubois** [comment]
YACReader is ok
franz is nok EDIT = create icon for this   DONE
Vivaldi is ok
makemkv --- build failed url wrong  <-<- build failed with chaser PENDING
mkv-extractor-qt5 --- build failed  <-<- build failed with chaser  PENDING
SVP4/SVPManager is ok
t-lasku --- build failed  EDIT installs with chaser !!!! DONE
KDE-Services ? services is ok 
xperia-theme-creator installing EDIT : installed - make icon for this -DONE
xperia-flashtool installing EDIT: installed - make icon for this -DONE
Master PDF Editor installing - ok - create new icon for this -DONE

**Comment by ahjolinna** [comment]
new version of t-lasku uploaded and it seems makemkv does download but it wont compile with qt5.7

**Comment by ahjolinna** [comment]
konversation
![spectacle nn5850](https://cloud.githubusercontent.com/assets/6993072/17526530/505200ec-5e70-11e6-94b7-988fdf1fdbc4.png)
octopi
![spectacle lh7555](https://cloud.githubusercontent.com/assets/6993072/17526636/ba7487f6-5e70-11e6-913a-7a6efb54704e.png)

**Comment by erikdubois** [comment]
What do you mean by KDE-Services ?

**Comment by erikdubois** [comment]
yacreader has 2 icons : YACReaderLibrary and YACReader (u have add this one with lowercase)

they work fine here - both point to same icon - yacreader

**Comment by erikdubois** [comment]
new version online here 
https://sourceforge.net/projects/sardi/files/?source=directory

**Comment by erikdubois** [comment]
systemsettings done

**Comment by erikdubois** [comment]
how do I get this dolphin look as above with the panel on the left?

**Comment by ahjolinna** [comment]
[kde-services](https://chakralinux.org/ccr/packages.php?ID=5558) is in ccr 

about dolphin, u can unlock "toolbar positions" (right-click) and then you can change the orientation

**Comment by ahjolinna** [comment]
those "white icons" arent yet fixed for breeze(light)..wasnt there some script for them?

**Comment by erikdubois** [comment]
that’s a major decision

let me think about it

**Comment by erikdubois** [comment]
![screenshot_20160810_105129](https://cloud.githubusercontent.com/assets/10594806/17547636/886a2518-5ee8-11e6-9920-4d2ef3ba1e31.png)
this will be a bit better

**Comment by ahjolinna** [comment]
grey is better than nothing, but I did notice that there are some/few that have a "black" version already, I dont know if it was left behind from the ardis time....and when I used the breeze dark it/they had become white again so it seemed to change

**Comment by ahjolinna** [comment]
I just updated to 7.4.3, one thing that I wonder why is the home button in toolbar "colored" (it was in previous versions also) ::
![spectacle sc8914](https://cloud.githubusercontent.com/assets/6993072/17604973/e2d8efb4-6020-11e6-8af9-f15d01001de8.png)

btw. I think Sardi Flat Majestic is my fav. icon theme..at least now:

![spectacle zm8914](https://cloud.githubusercontent.com/assets/6993072/17605259/311678da-6022-11e6-80ae-6aabe37f457f.png)

**Comment by ahjolinna** [comment]
btw. about those white/grey icons....maybe a dark variant could added as a optional "patch"  (in/for PKGBUILD)...it would be better because it can be hard to see that grey version if u dont have good monitor....with an cheap monitor grey icon will easily blend with breeze (light) theme

P.S. I notice this error: Invalid Context= "Notifications" line for icon theme:  "/usr/share/icons/Sardi/scalable/notifications/"

**Comment by ahjolinna** [comment]
I made that change to the[ chakra CCR PKGBUILD](https://chakralinux.org/ccr/packages.php?ID=7803) ....but that error is still there/present
