### ISSUE TITLE
[kde] random problem with plasma-pa -audio applet

### ISSUE THREAD

**Issue by ahjolinna** [erikdubois/Sardi#20]
(I'm using arch, and sardi 9.3-3)

the KDE's audio applet "[plasma-pa](https://github.com/KDE/plasma-pa)" has icon missing on some of the sardi version... the "normal" sardi works fine, looks : 
![image](https://user-images.githubusercontent.com/6993072/28486636-bcf9f826-6e8c-11e7-8069-1bb9bbe5767d.png)

some don't and looks like this: 

![image](https://user-images.githubusercontent.com/6993072/28486617-63361536-6e8c-11e7-98ba-945d7cd5db22.png)

where it works :
 Sardi, -Colora, -Flat, -Flexible, -Ghost Flexible, -Orb Colora

where it doesnt : 
Sardi Arc, -Flat Colora, -Flat Evopop, -Flexible Colora, -Flexible Luv Colora, -Ghost Flexible Colora, -Mono, -Mono Archlabs, -Mono Mint Colora, -Mono Mint-X-Grey, -Mono Numix, -Mono Numix Colora, -Mono Papirus Colora, -Mono Vertexed, 

------

surfn has this same issue also

**Comment by ahjolinna** [comment]
oh and this also affects the mic/capture device:
![image](https://user-images.githubusercontent.com/6993072/28486962-e59465ce-6e90-11e7-98d3-f02648fd7516.png)

-----
my system:
```
inxi -b
System:    Host: arch-anywhere Kernel: 4.11.11-1-ck-skylake x86_64 (64 bit) Desktop: KDE Plasma 5.10.4
           Distro: Arch Linux
Machine:   Device: desktop Mobo: ASUSTeK model: Z170 PRO GAMING v: Rev X.0x UEFI: American Megatrends v: 2003 date: 09/19/2016
CPU:       Quad core Intel Core i5-6600K (-MCP-) speed/max: 4399/4400 MHz
Graphics:  Card: NVIDIA GM204 [GeForce GTX 970]
           Display Server: x11 (X.Org 1.19.3) driver: nvidia Resolution: 1920x1080@60.00hz, 1920x1080@60.00hz
           OpenGL: renderer: GeForce GTX 970/PCIe/SSE2 version: 4.5.0 NVIDIA 381.22
Network:   Card: Intel Ethernet Connection (2) I219-V driver: e1000e
Drives:    HDD Total Size: 12114.3GB (94.4% used)
Info:      Processes: 354 Uptime: 3 days Memory: 8242.2/15966.9MB Client: Shell (bash) inxi: 2.3.23 
```

**Comment by ahjolinna** [comment]
I thought I forgot something: KDE's new comic book reader [Peruse](https://peruse.kde.org/) : https://github.com/KDE/peruse

has 2 "apps" : [peruse](https://github.com/KDE/peruse/tree/master/src/app/icon) & [peruse-creator](https://github.com/KDE/peruse/tree/master/src/creator/icon) (icon names)

**Comment by erikdubois** [comment]
KDE gives me worries
did you fix it...
ArchMerge KDE will take me a while to get to

**Comment by erikdubois** [comment]
I will postpone this one till we do ArcoLinuxD-Plasma

**Comment by erikdubois** [comment]
now it is time to tell me more issues
soon to start plasma

**Comment by ahjolinna** [comment]
maybe a separate bug report for just KDE? at least the toolbar icons (for many kde apps) need to needs to be fixed, for example dolphin (file manager)

(I dont know how ArcoLinuxD-Plasma works, I'm currently using openSUSE tumbleweed which works really well.)

**Comment by erikdubois** [comment]
so I am on ArcoLinuxB-Plasma these days
can we update the issues?

**Comment by erikdubois** [comment]
reading this text here
still an issue?
put in separate issue
icon per icon if it is
