### ISSUE TITLE
Sardi Icons pixelated on Cinnamon 18.3

### ISSUE THREAD

**Issue by Auerilas** [erikdubois/Sardi#24]
Hi,
I just installed Sardi and I love the flexibility and customization. However, on my Cinnamon 18.3 desktop, the icons look a little pixelated (the app icons in the menu and window list). 

For example, here is Minty Y icons which are crisp and clear

![mint-y](https://user-images.githubusercontent.com/9372234/34500561-8361bc26-efc8-11e7-9fd1-b9bee0dec778.png)

and the Numix icons, also clear

![numix](https://user-images.githubusercontent.com/9372234/34500567-902206fa-efc8-11e7-9a01-d851acac8538.png)

But for some reason, the Sardi icons in the menu and along the window list at the top didn't scale correctly and look pixelated

![sardi flexible](https://user-images.githubusercontent.com/9372234/34500587-a210d846-efc8-11e7-8507-07a3ba4c5a8c.png)

although the alt-tab icons look great

![sardi flexible alt tab](https://user-images.githubusercontent.com/9372234/34500596-ab4dc090-efc8-11e7-9859-b0756e95f24a.png)

Any thoughts on how to resolve this issue? I've gone into the index.theme and tried to change the size defaults, but that didn't seem to do anything.

Thanks!

**Comment by erikdubois** [comment]
Sardi has svg format the others have png format...
I think you need to see what changed on Linux Mint so that svg is not looking nice anymore.

**Comment by erikdubois** [comment]
i was just on linux mint 18.3 cinnamon
they looked ok here
closing but following it up
