### ISSUE TITLE
icon=zotero

### ISSUE THREAD

**Issue by erikdubois** [erikdubois/Sardi#265]
mention on forum
https://arcolinuxforum.com/viewtopic.php?f=49&t=2253&p=9146#p9146

**Comment by TheCrazyRabbit13** [comment]
The folder with the wrong icon is /usr/share/icons/Sardi-Flat/scalable/apps. How can I send you my icon because GitHub doesn't support .svg?

**Comment by erikdubois** [comment]
mail it to me 
erik.dubois@gmail.com

**Comment by TheCrazyRabbit13** [comment]
Done. Hope everything's alright with it. And thank you for your work Erik. :-)
