### ISSUE TITLE
[REQUEST] Icon Set Variant With Folders/Places Icons As Circles

### ISSUE THREAD

**Issue by ghost** [erikdubois/Sardi#28]
Hello! A request, not an issue... Currently, almost all of the icons for Sardi are circles, and the set is super complete, which I love... Except for the folders and places icons, like with the file manager and folders in it. Would a variant of the icon set with folders that match the rest of the set be possible? Another reason I bring this up is because the desktop folder icon is a circle anyway, but the others aren't, so it gave me some hope. Either way, thanks for this amazing icon set! Absolutely my favorite. 💙

**Comment by erikdubois** [comment]
time to close those items
