### ISSUE TITLE
expanding to mobile (android, SailfishOS/ubuntu-touch)??

### ISSUE THREAD

**Issue by ahjolinna** [erikdubois/Sardi#3]
I have been using ardis black version a lot on my Sony Xperia Z3+ / Nokia's Z-launcher, but it seems to be dead (nitrux team doesn't seem to have any intrest to update it).

So I wonder if u have any intrest to expand to mobile?

I'm personally more intrested in [SailfishOS](http://sailfishos.org/) after the Turing Phone thing.
## if u dont know what SailfishOS (or Turing) is...then:

SailfishOS is made by [Jolla](http://jolla.com/) that was created from ex-nokia[ MeeGo-linux](http://muropaketti.com/artikkelit/the-story-of-nokia-meego) team.
SailfishOS uses Qt5, btrfs, systemd, wayland....its based on [MER project](http://merproject.org/) (its the core)

[SailfishOS 2.0 demo](https://www.youtube.com/watch?v=j2TnTbShEwA)

Turing Robotic Industries announced a while ago that they will move away from Android to SailfishOS and they will move their company and their manufacturing to Finland, apparently the reasons have been because of NSA and interest in ex-nokia engineers and the manufacture facilities in Oulu.

Apparently the phone will be updated (before the release) to Snapdragon 820 from 801. The phone also has 3GB of RAM, 16GB, 64GB, and 128GB of internal memory, 5.5-inch FullHD display and 8MP and 13MP cameras.....and also 3000 mAh battery. It also has fingerprint sensor and  end to end encryption .....and made from liquid metal

homepage: https://www.turingphone.com/
[preview/demo of the old snapdragon 801 version](https://youtu.be/9QdgupPx40k)
[commercial/ads video](https://www.youtube.com/watch?v=_02PgHgXb_o)

Turing Robotic Industries announced (finally) that the Turing Phone shipments starts july 12.

....sorry for this ^small^ advertising rant :D

**Comment by erikdubois** [comment]
Well I have the icons and I have a samsung android laying around.
First step would be the get my icons on the machine.
That was something I would like to figure out.
Any ideas or links.
For the rest I will keep my eye on this development. Looks promising.

**Comment by ahjolinna** [comment]
well I would read this: http://forum.xda-developers.com/showthread.php?t=916814

and for SailfishOS I found this : https://github.com/fravaccaro/themepacksupport-sailfishos/wiki/Get-started and 3rd party repo: https://openrepos.net/

**Comment by erikdubois** [comment]
ok thanks closing the issue now
now i have an idea what to google ...

**Comment by ahjolinna** [comment]
has there been any progress?
btw. you can now offically buy the [intex aqua](http://www.intex.in/mobile/smartphone/aqua-fish/) -SailfishOS phone for 75€ from [ebay](http://www.ebay.in/itm/Intex-Aqua-Fish-4G-LTE-with-Qualcomm-Snapdragon-5-2GB-RAM-16-GB-8MP-/282098603976)
its orginally only for the indian market, but those who still want it can now still buy it (there are also 2 phones that are only for russian market)
btw. SailfishOS supports android apps, it uses Alien Dalvik (optional)

maemo/meego/sailfishOS [forum-page](http://talk.maemo.org/)
Jolla/sailfish [FB-fanpage](https://www.facebook.com/groups/jollapioneer/)

---

meanwhile in Finland/Helsinki: [ZZ Top's Billy Gibbons as a street musician](https://youtu.be/YHUQNxggT_k) :D

**Comment by erikdubois** [comment]
not a priority right now
i keep it in mind though

**Comment by ahjolinna** [comment]
about android icons, maybe [RemixOS](http://www.jide.com/remixos) project could help, instead of using phone:

![1469440280002_ndc8ma_update](https://cloud.githubusercontent.com/assets/6993072/17605592/ce478e40-6023-11e6-9670-9beec9c3187d.png)

[small 40€ device](http://www.jide.com/mini)
[and/or PC version](http://www.jide.com/remixos-for-pc)

**Comment by ahjolinna** [comment]
Now with [Nokia 6](http://www.gsmarena.com/androidpowered_nokia_6_marks_the_brands_return_to_smartphones-news-22612.php) released to chinese market and more to come on end of february (globally), I need to ask again :D do u think this is the year of  the mobile version for sardi? ;D 

PS. [Nokia 6 camera prevew video](https://www.youtube.com/watch?v=eUL4psdvNE4)...
[Nokia 6 specifications](http://www.androidpure.com/nokia-6-with-5-5-fhd-sd430-4-gb-ram-announced-in-china-for-1699-yuan)

-       Display : 5.5 inch 1080p 2.5D curved glass display, Corning Gorilla Glass 3 protection
-       CPU : Octa-Core Qualcomm Snapdragon 430 processor
-       GPU: Adreno 505
-       RAM : 4 GB LPDDR3
-       Storage: 64 GB, expandable up to 128GB with microSD
-       OS: Android 7.0 (Nougat)
-       Misc: Dual SIM, Fingerprint sensor, Dual speakers, Dual smart amplifiers (TFA9891), Dolby Atmos
-       Camera : 16 MP rear camera with dual-tone LED flash, PDAF, f/2.0 aperture and 8 MP front shooter, f/2.0 aperture, 84˚ wide-angle lens
-       Dimensions: 154 x 75.8 x 7.8 mm
-       Connectivity : 4G LTE, WiFi 802.11 b/g/n, Bluetooth 4.1, GPS, USB OTG
-       Battery : 3000 mAh
-       Audio : DOLBY Atmos support for better audio

...apprently the aluminum body takes over 11h to make, that is really nice for 250$ phone
