### ISSUE TITLE
Missing "Applications" icons

### ISSUE THREAD

**Issue by algent-al** [erikdubois/Sardi#303]
OS: Solus Budgie and Gnome

Hi! I found that there are missing icons in sardi-icons theme. 
![Applications-menu](https://user-images.githubusercontent.com/46356616/107876467-7165a980-6ec6-11eb-8923-151e04c7c3fb.png)

And this icon:
![Applications-gnome-settings](https://user-images.githubusercontent.com/46356616/107876481-8a6e5a80-6ec6-11eb-87e3-71f3f540d3f9.png)

I think they are loaded from Adwaita theme and they are in these locations:
`/usr/share/icons/Adwaita/scalable/apps/preferences-desktop-apps.svg`
`/usr/share/icons/Adwaita/${size}x${size}/apps/preferences-desktop-apps-symbolic.symbolic.png`
where ${size} is 16, 24, 32, 48, 64, 96

**Comment by algent-al** [comment]
Hi @erikdubois. I am trying new release 21.03 released today, and found that the Applications icon in the menu is fine, but the other one in gnome-settings it looks like a white circle.
I think this icon should be monocromatic.

Currently it looks like this for all Sardi icons except for Sardi-Ghost-Flexible-* icons:
![Applications](https://user-images.githubusercontent.com/46356616/112891732-c6592a00-90d8-11eb-9eb7-1db993e4116c.png)

So I copied `Sardi-Ghost-Flexible/scalable/categories/applications-other.svg` to `${icons}/scalable/apps/preferences-desktop-apps-symbolic.svg` to fix it. And now it looks like this:
![gnome-settings](https://user-images.githubusercontent.com/46356616/112892167-47b0bc80-90d9-11eb-9d8c-aed0a1342f5f.png)

**Comment by erikdubois** [comment]
refresh your icon cache
