### ISSUE TITLE
tusk 

### ISSUE THREAD

**Issue by erikdubois** [erikdubois/Sardi#32]
Icon=tusk-app
https://plus.google.com/u/0/102245404178181086307/posts/1Ph12AiM5av?cfem=1

**Comment by erikdubois** [comment]
done

**Comment by TC68** [comment]
recent updates to tusk seem to have
Icon=tusk
and I have had to manually change it in /usr/share/applications/tusk.desktop
Mint 19.1, Kernel 4.15, Cinnamon 4.09
