### ISSUE TITLE
openSUSE YaST control center

### ISSUE THREAD

**Issue by ahjolinna** [erikdubois/Sardi#321]
I just got a new PC and installed openSUSE tumbleweed on it and then tried your icons for a long time and notice that these icons where missing from YaST

![image](https://user-images.githubusercontent.com/6993072/130406053-e2f8621f-283b-404f-998c-dab005a16bb7.png)
(for some reason kvantum themes doesn't work now on yast, which is why so ugly)

these seems to be the icons that are missing: https://github.com/yast/yast-yast2/tree/master/data/icons/hicolor/scalable/apps
...there could be some other smaller icons missing within the YasT

------

```


             .;ldkO0000Okdl;.                root@localhost
         .;d00xl:^''''''^:ok00d;.            OS: openSUSE 20210820
       .d00l'                'o00d.          Kernel: x86_64 Linux 5.13.12-1-default
     .d0K^'  Okxoc;:,.          ^O0d.        Uptime: 6h 57m
    .OVVAK0kOKKKKKKKKKKOxo:,      lKO.       Packages: 2444
   ,0VVAKKKKKKKKKKKKK0P^,,,^dx:    ;00,      Shell: bash 5.1.8
  .OVVAKKKKKKKKKKKKKk'.oOPPb.'0k.   cKO.     Disk: 16T / 20T (83%)
  :KVAKKKKKKKKKKKKKK: kKx..dd lKd   'OK:     CPU: AMD Ryzen 7 5700G with Radeon Graphics @ 16x 3.8GHz
  lKlKKKKKKKKKOx0KKKd ^0KKKO' kKKc   lKl     GPU: NVIDIA GeForce RTX 3060 Ti
  lKlKKKKKKKKKK;.;oOKx,..^..;kKKK0.  lKl     RAM: 7774MiB / 15316MiB
  :KAlKKKKKKKKK0o;...^cdxxOK0O/^^'  .0K:    
   kKAVKKKKKKKKKKKK0x;,,......,;od  lKP     
   '0KAVKKKKKKKKKKKKKKKKKK00KKOo^  c00'     
    'kKAVOxddxkOO00000Okxoc;''   .dKV'      
      l0Ko.                    .c00l'       
       'l0Kk:.              .;xK0l'         
          'lkK0xc;:,,,,:;odO0kl'            
              '^:ldxkkkkxdl:^'              

```

**Comment by erikdubois** [comment]
I think you are on plasma

Sardi is not created for plasma

These are for plasma

https://github.com/erikdubois/arcolinux-candy-beauty

https://github.com/erikdubois/Surfn-Plasma-Dark

cheers
erik

Op ma 23 aug. 2021 om 09:22 schreef Alexander Waldemar Ahjolinna <
***@***.***>:

**Comment by ahjolinna** [comment]
yes I am on plasma, but YaST is a openSUSE control center app and its for all DE's

**Comment by erikdubois** [comment]
tell me if the other links are any good
