### ISSUE TITLE
No theme index file

### ISSUE THREAD

**Issue by j4media** [erikdubois/Sardi#336]
Hi Erik, first off, thanks for your work on the Sardi Icon set!  I came across and issue when using change-color.sh in the Sardi-Ghost-Flexible set.  I can run the script just fine, but when it's done executing I get an error "gtk-update-icon-cache: No theme index file". When I run the create-new-icon-theme.cache.sh before changing the color it creates the new cache file just fine.

There's clearly an index.theme file in my folder after the color change so not sure why the error is being thrown.

**I resolved this issue, needed to run create-new-icon-theme.cache.sh as sudo.** 

Leaving this here in case someone else runs into the same problem.

**Comment by erikdubois** [comment]
if you do this on /usr/share/icons 

then yes that makes sense

I usually copy/paste everything on my desktop
run scripts
and endresult goes in /home/erik/.icons
