### ISSUE TITLE
Pop OS icons Sardi style for Cosmic Desktop

### ISSUE THREAD

**Issue by FlexCoreOS** [erikdubois/Sardi#338]
Icons and desktop files here --->  https://github.com/pop-os/cosmic/tree/master_hirsute/usr/share

pop-cosmic-applications
pop-cosmic-launcher
pop-cosmic-workspaces

*.desktop files same as icon names

If you need any more information, please let me know.  Thank you for your hard work on Sardi and Arcolinux

**Comment by erikdubois** [comment]
![image](https://user-images.githubusercontent.com/10594806/138126616-c7a9305c-aadf-4a75-99a9-5dfa347fc5cc.png)
