### ISSUE TITLE
[REQUEST] pycharm icon

### ISSUE THREAD

**Issue by stewic** [erikdubois/Sardi#350]
Hello, I'd like to put an icon request for a Sardi Flat icon for pycharm please. SVG file available https://commons.wikimedia.org/wiki/File:PyCharm_Icon.svg

$ cat pycharm-community.desktop 
[Desktop Entry]
Version=1.0
Type=Application
Name=PyCharm Community Edition
Icon=${SNAP}/bin/pycharm.png
Exec=pycharm-community %f
Comment=Python IDE for Professional Developers
Categories=Development;IDE;
Terminal=false
StartupWMClass=jetbrains-pycharm-ce
StartupNotify=true

**Comment by erikdubois** [comment]
thanks

**Comment by erikdubois** [comment]
we have that one already

do not install via snap and it will be fine or change the Icon line
Icon=... choose the name from the image without svg
![pycharm](https://user-images.githubusercontent.com/10594806/154972793-c2dd621b-1ee6-47b8-8691-627c15a10669.png)
There are more names...
