### ISSUE TITLE
Big Icons in Evolution settings dialog!

### ISSUE THREAD

**Issue by gotolindak73** [erikdubois/Sardi#4]
I love the Sardi icons but there seems to be an issue in Evolution. I'm running Mint Cinnamon 18 with Sardi Icons. Attaching a screenshot on my settingsdialog. 

Best Regards 
Linda
![skarmbild fran 2016-07-23 10-53-48](https://cloud.githubusercontent.com/assets/20610372/17077122/ef6918dc-50c4-11e6-8f6f-545623f11f3d.png)

**Comment by erikdubois** [comment]
to be checked - checked and confirmed

**Comment by erikdubois** [comment]
issue should be solved now
i changed already two icons to the Sardi look
others will follow
download sardi 7+ latest

**Comment by gotolindak73** [comment]
Works great now! :-)
