### ISSUE TITLE
Only some icons change theme

### ISSUE THREAD

**Issue by kingogames** [erikdubois/Sardi#5]
Not sure if this is an issue with the icons or not, but it is strange. I set my icon theme to Sardi, then changed to Sardi Colora, now I want to change back, but not all of my folders changed back. Do you know why that would happen?

Thanks!!
![screenshot from 2016-09-09 22 10 20](https://cloud.githubusercontent.com/assets/13295856/18407894/1af9ce92-76db-11e6-840f-2a825296809c.png)

**Comment by erikdubois** [comment]
On KDE/Plasma... that is an issue. Logging off  and on did the trick for me.
What system are you on?
Sorry I seem to have missed this issue.
