### ISSUE TITLE
Icon request for Gramps

### ISSUE THREAD

**Issue by TC68** [erikdubois/Sardi#58]
/usr/share/applications/gramps
icon=gramps
Thanks Erik

**Comment by erikdubois** [comment]
genealogy

**Comment by TC68** [comment]
thanks


Tim Chambers | Principal Hydrogeologist, Accredited Contaminated Land Auditor (NSW EPA, EPA VIC), EIANZ CEnvP(SC) | MEngSci, BA Hons, BSc | Tim.Chambers@arcadis.com<mailto:Tim.Chambers@arcadis.com>
Arcadis | Level 16, 580 George Street, Sydney | NSW 2000 | Australia
T. +61 2 8907 3983 | M. +61 458 888 033
www.arcadis.com/au<http://www.arcadis.com/au>
[CHAMBERS Timothy_Site_Contamination_Electronic_Seal]

[Remediation-redefined_email-signature]<arcad.is/rremail>


Be green, leave it on the screen.

[cid:image004.png@01D27D5C.C38D8260]<https://www.linkedin.com/company/arcadis-australia-pacific>[cid:image008.png@01D27D5C.E2197C70]<https://twitter.com/arcadisglobal>
Registered office: Level 16, 580 George Street, Sydney NSW 2000 Australia   ABN 76 104 485 289

**Comment by TC68** [comment]
Thanks Erik  It works perfectly and looks as good as the others
