### ISSUE TITLE
Orion icon missing

### ISSUE THREAD

**Issue by ahjolinna** [erikdubois/Sardi#6]
hi, again

so about the orion -twitch client app, the current icon/logo [is this one](https://github.com/alamminsalo/orion/blob/master/resources/orion.svg).

PS. if you are intrested to try it on arch you should know that the AUR version doesn't work that well, at least by default...thats why I had to remake the damn pkgbuild to chakra/ccr, you can use my [pkgbuild in ccr](https://chakralinux.org/ccr/packages.php?ID=7817) on arch it should work just fine

**Comment by erikdubois** [comment]
ok tell me what name the icon should have in order to work?

**Comment by erikdubois** [comment]
I gave it the name orion.svg. Let me know if this works.

**Comment by ahjolinna** [comment]
yeah that should work, I will check it soon

**Comment by erikdubois** [comment]
version 7.7.7

**Comment by ahjolinna** [comment]
seems to work, closing
