### ISSUE TITLE
tmp folder has wrong theme

### ISSUE THREAD

**Issue by ahjolinna** [erikdubois/Sardi#7]
the tmp folder in root seems to be "little bit wrong", at least in Sardi Flat Majestic:
![screenshot_20161011_175225](https://cloud.githubusercontent.com/assets/6993072/19275162/806c7bd0-8fdb-11e6-8fcb-579767c52177.png)

**Comment by erikdubois** [comment]
it looks ok here on a linux mint 18 cinnamon.
Remember my guess is that you are still on a kde system. Changing icons and not logging off and on or rebooting solves my issues I had with any icon theme on Chakra I think it was you use.
![sardimajestic](https://cloud.githubusercontent.com/assets/10594806/19301254/c9d4a076-905e-11e6-9bd6-0557ec876cdb.jpg)

**Comment by ahjolinna** [comment]
it has been a problem for a while just been lazy to report it...and yes, I use KDE/ChakraOS

**Comment by ahjolinna** [comment]
![screenshot_20161012_110555](https://cloud.githubusercontent.com/assets/6993072/19302220/ebfd8598-906b-11e6-8e58-3fc0ff9d9e18.png)

**Comment by ahjolinna** [comment]
if you notice that the tmp folder has the right theme in "preview mode", but in the "icon selection" thing its still wrong

PS. this is not related but everytime I open a app from terminal I see this: 

```
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Sardi Flat/16/panel/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Sardi Flat/22/panel/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Sardi Flat/24/panel/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Sardi/16/panel/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Sardi/22/panel/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Sardi/24/panel/"
Invalid Context= "Notifications" line for icon theme:  "/usr/share/icons/Sardi/scalable/notifications/"

```

**Comment by erikdubois** [comment]
These seem to be all related to KDE/Plasma. Not sure why and frankly you know that KDE/Plasma is the least of my concerns. Closing this. No issue on any other distro. If you figure it out, please share the solution.
