### ISSUE TITLE
Icons looking broken on MX 16.1

### ISSUE THREAD

**Issue by ktlinux** [erikdubois/Sardi#72]
I have an old laptop that is still running the Debian 8 based MX Linux 16.1. Your icons appear broken on my system. like, literally. [This is how it looks like using the basic Sardi theme](https://imgur.com/a/8AFWoo2). And the other variations do not look better either.

Is there any fix for this?

**Comment by erikdubois** [comment]
see what you can find about svg and libraries for it on your distro
there lies the solution since all other 80+ distro's look good.
