### ISSUE TITLE
[issue?] dropbox plasma taskmanager icon

### ISSUE THREAD

**Issue by ahjolinna** [erikdubois/Sardi#8]
when I use the Sardi flat majestic icon theme the dropbox taskmanager icon looks like this: 
![spectacle m23168](https://cloud.githubusercontent.com/assets/6993072/19823167/e538b316-9d6f-11e6-88de-20b4156946e4.png)

with icon breeze it looks like this : 
![spectacle s23168](https://cloud.githubusercontent.com/assets/6993072/19823133/b6322b42-9d6f-11e6-9fa1-8cf985301640.png)
I think it uses [this](https://aur.archlinux.org/packages/dropbox-plasma-dark-icons-git/) what I have installed

Okay I don't know if this is a issue, but I think it looks horrendous

**Comment by erikdubois** [comment]
that is ok for me. Those are Breeze icons nothing to do with sardi. Thats
what you get when you mix themes.

Op vr 28 okt. 2016 om 23:39 schreef Alexander Waldemar Ahjolinna <
notifications@github.com>:

**Comment by ahjolinna** [comment]
oh boy, it seems there was some misapprehension.
the point with breeze icon thing was to show that it actually works and how it could look..
for my the Sardi icon looks really bad/broken, I don't understand why it can't be the normal/same icon that used in "menu"...like Input Method has

**Comment by ahjolinna** [comment]
also I get that ugly dropbox icon with all plasma themes if I use Sardi....so its Sardi icon "problem"
if I change the icon theme and it has a dropbox tray icon it I will that one....
only thing I dont know is that if the plasma theme has the icons for that app which one will it use, the plasma themes or icon themes

**Comment by ahjolinna** [comment]
do u think this looks great, and looks like its part of sardi icon set? 
![gif img](http://i.imgur.com/BOc9nih.gif)

apprently dropbox uses the accient/deprecated Xembed .... at least about a year ago I don't know if this has changed 

ps. this is not releated, but I just notice this: 
![image](https://cloud.githubusercontent.com/assets/6993072/21865574/60ad3b06-d84f-11e6-923f-0434f0d49569.png)
only place where I can see the actual "sardi themed" icon on sytemtray is on that one....but for some reason its only the "pop-up" version


picture of my whole systemtray: 
![image](https://cloud.githubusercontent.com/assets/6993072/21865687/dd135fd6-d84f-11e6-8d46-da290d763d65.png)


[Theming Application Icons in the Systemtray](https://techbase.kde.org/Development/Tutorials/Plasma5/ThemeDetails#Theming_Application_Icons_in_the_Systemtray)

**Comment by erikdubois** [comment]
there is a dropbox icon that looks like that in sardi.  But on my distro's the icons are stored in the dropbox-dist folder. The sardi icons are not loaded in our distro's. We have to copy paste the icons to this hidden folder every time we have an update. Lately I leave the standard icon of dropbox. They look with all the other white icons. What distro did you have again?

**Comment by ahjolinna** [comment]
I'm currently using manjaro-kde, as my chakraOS install broke and the ISO doesn't work for me

**Comment by erikdubois** [comment]
You know KDE is the one desktop I am not working on and every time I leave it I am happy again. Sorry for that. I respect that you are happy with KDE.
